### PR TITLE
Working xdebug for mac users

### PR DESCRIPTION
**Pull request by tomhaj**
According to this **[article](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds)** mac users should use different hostname in xdebug. Setting it to `docker.for.mac.localhost` will resolve problems

### CODE REVIEW

**Comment by codeliner** [comment]
ping @sandrokeil

**Comment by sandrokeil** [comment]
@tomhaj Thank you for your PR. Can you remove the env var `ENV XDEBUG_HOST=172.17.0.1 ` from the fpm config files please. It is not used there in favor of `xdebug.remote_connect_back=1`

**Comment by tomhaj** [comment]
@sandrokeil fixed. Please check changes again and merge if ready.

**Comment by sandrokeil** [comment]
New Docker image tags are on the way.

**Pull request merged**
