### PR TITLE
Load static config with rabbit mgmt

### PR DESCRIPTION
**Pull request by codeliner**
Found a nice way to load configuration from file: https://medium.com/@thomasdecaux/deploy-rabbitmq-with-docker-static-configuration-23ad39cdbf39

With this PR we get rid of the entrypoint wrapper and instead use a config file which gets loaded by the mgmt plugin.

This allows users of the image to override the configuration and for example configure exchanges and queue bindings. You can set it up via the mgmt ui and then export configuration.

In your docker-compose you then mount your local defintions.json to `/opt/definitions.json` like described in the linked article.

/cc @basz

### CODE REVIEW

**Comment by basz** [comment]
I think I played with this method too, but can't remember now why I did not pursue it further...

**Comment by codeliner** [comment]
@basz Would be interesting. If you remeber the reason then let me know! It works like a charm so far. Tried it with exchange and queue configuration, too.

@bweston92 your thoughts. Can you see any drawbacks?

**Comment by prolic** [comment]
I think this is the best solution, I completely forgot about this feature.

**Comment by basz** [comment]
use it. I tried to make a container that could be configured on runtime - once I let that 'requirement' go I should have gone back to using this method.

**Pull request merged**
